FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

# Disable Python downloads, because we want to use the system interpreter
# across both images. If using a managed Python version, it needs to be
# copied from the build image into the final image; see `standalone.Dockerfile`
# for an example.
ENV UV_PYTHON_DOWNLOADS=0

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY ./opengaterag/api/ opengaterag/api/api

RUN --mount=type=cache,target=/root/.cache/uv \
    uv venv
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv pip install .

# Runtime stage
FROM python:3.12-slim AS runtime

RUN groupadd --gid 1100 opengaterag && \
    useradd --home /api --gid 1100 --uid 1100 opengaterag

# Only runtime dependencies
RUN apt-get update && apt-get install -y \
    libpq5 \
    poppler-utils \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Set a non-root user
USER opengaterag
WORKDIR /

# Copy application from builder
COPY --from=builder --chown=opengaterag:opengaterag opengaterag/api /api
COPY --from=builder --chown=opengaterag:opengaterag /.venv /.venv
COPY --chown=opengaterag:opengaterag ./scripts/ /scripts/

ENV PATH="/.venv/bin:${PATH}"
ENV PYTHONPATH="/api"
ENV PROMETHEUS_MULTIPROC_DIR="/tmp/prometheus_multiproc"
ENV CONFIG_FILE="/config.yml"

# Final stage
FROM runtime AS final

RUN chmod u+x /scripts/startup_api.sh
CMD ["/bin/bash", "-c", "/scripts/startup_api.sh"]
